# Generated by Django 6.0 on 2026-01-01 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=15)], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('LANDLORD', 'Landlord'), ('TENANT', 'Tenant'), ('SERVICE_PROVIDER', 'Service Provider'), ('ADMIN', 'ADMIN')], max_length=30, null=True),
        ),
    ]
