# Generated by Django 6.0 on 2026-01-03 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=13), django.core.validators.MaxLengthValidator(limit_value=15)], verbose_name='phone number'),
        ),
    ]
