# Generated by Django 6.0 on 2026-01-04 07:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rwanda', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='properties.city')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Single Room', 'Single Room'), ('Apartment', 'Apartment'), ('House', 'House'), ('Villa', 'Villa'), ('Studio', 'Studio'), ('Duplex', 'Duplex'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Office', 'Office')], default='House', max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Under Maintenance', 'Under Maintenance')], default='Available', max_length=50)),
                ('date_of_listing', models.DateTimeField(auto_now_add=True, null=True)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('n_bed_rooms', models.IntegerField(blank=True, default=1, null=True)),
                ('n_bath_rooms', models.IntegerField(blank=True, default=1, null=True)),
                ('surface', models.IntegerField(blank=True, default=1, null=True)),
                ('has_wifi', models.BooleanField(default=False)),
                ('parkings', models.IntegerField(blank=True, default=0, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='houses')),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='houses')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='houses')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='houses')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='houses')),
                ('on_map', models.TextField(blank=True, null=True)),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='properties.province'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('guests', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='properties.district')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='properties.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='properties.cell')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='properties.village'),
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('guests', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='properties.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
