# Generated by Django 6.0 on 2025-12-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='houses'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='houses'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='houses'),
        ),
        migrations.AddField(
            model_name='house',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='houses'),
        ),
        migrations.AddField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses'),
        ),
        migrations.AddField(
            model_name='house',
            name='parkings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
