# Generated by Django 6.0 on 2026-01-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='landlord',
        ),
    ]
