# Generated by Django 6.0 on 2025-12-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_house_image_four_house_image_one_house_image_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='on_map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
