# Generated by Django 6.0 on 2026-01-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_house_on_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Apartment', 'Apartment'), ('House', 'House'), ('Villa', 'Villa'), ('Studio', 'Studio'), ('Duplex', 'Duplex'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Office', 'Office')], default='House', max_length=50),
        ),
    ]
