# Generated by Django 6.0 on 2026-01-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Refused', 'Refused')], default='Pending', max_length=50),
        ),
    ]
